spring.application.name=crm

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.open-in-view=false

# Active profile (override in production)
spring.profiles.active=local
