spring.application.name=crm

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.open-in-view=false

# Active profile (override in production)
spring.profiles.active=local

# Pagination
spring.data.web.pageable.default-page-size=5

# CORS
app.cors.allowed-origins=

# JWT
jwt.secret=15d0eca6799a5c5e8ab4caa8fd598963e633fc04ae28f32d3a6cec05b62e77aa
jwt.expiry.hours=24
