package com.lmi.crm.enums;

public enum AlertType {
    DUPLICATE_PROSPECT,
    PROSPECT_CONVERSION_REQUEST,
    ASSOCIATE_CREATION_REQUEST,
    ASSOCIATE_DEACTIVATION_REQUEST,
    LICENSEE_DEACTIVATION_REQUEST,

    // to licensee FOR EMAIL ONLY
    PROSPECT_PROTECTION_WARNING,

    // to licensee FOR EMAIL ONLY
    PROSPECT_UNPROTECTED,
    OWNERSHIP_CLAIM_REQUEST,
    PROTECTION_EXTENSION_REQUEST,
    GROUP_DELETION_REQUEST,
    TASK_REMINDER
}
