package com.lmi.crm.enums;

public enum AuditActionType {
    USER_REGISTERED,

    PROSPECT_CREATED,
    PROSPECT_UPDATED,
    PROSPECT_DUPLICATE_ATTEMPT,
    PROSPECT_UNPROTECTED,
    PROSPECT_CONVERSION_REQUESTED,
    PROSPECT_CONVERSION_APPROVED,
    PROSPECT_CONVERSION_REJECTED,
    PROVISIONAL_APPROVED,
    PROVISIONAL_REJECTED,

    GROUP_CREATED,
    GROUP_UPDATED,
    GROUP_DELETED,

    LICENSEE_CREATED,
    LICENSEE_DEACTIVATED,

    ASSOCIATE_CREATED,
    ASSOCIATE_DEACTIVATED,
    ASSOCIATE_REQUEST_APPROVED,
    ASSOCIATE_REQUEST_REJECTED,

    ADMIN_CREATED,
    ADMIN_UPDATED,
    ADMIN_DEACTIVATED,

    RESOURCE_UPDATED,
    RESOURCE_DELETED
}
